events {}

http {
    server {
        listen 443 ssl;
        server_name mait-all.42.fr;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

		root /var/www/html;
		index index.php index.html;

		# wordpress - main location
		location / {
			try_files $uri $uri/ /index.php?$args;
		}

		# serving adminer via reverse proxy
		location /adminer {
			proxy_pass http://adminer:8080;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
    	}

		# serving static_site via reverse proxy
		location /static_site {
			proxy_pass http://static_site:80/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		# serving portainer service via reverse proxy
		location /portainer/ {
			proxy_pass http://portainer:9000/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;
		}

		# serving cadvisor service via reverse proxy
		location /cadvisor/ {
			proxy_pass http://cadvisor:8080/;
			proxy_set_header Host $host;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_set_header X-Forwarded-Proto $scheme;

			proxy_redirect / /cadvisor/;
		}

		# serving wordpress via fastcgi
		location ~ \.php$ {
			fastcgi_pass wordpress:9000;
			fastcgi_index index.php;
			fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;
			include fastcgi_params;
		}

		# deny .ht files
		location ~ /\.ht {
			deny all;
		}
    }
}
