listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=YES

# chroot user to their home directory
chroot_local_user=YES
allow_writeable_chroot=YES

# Passive mode ports
pasv_enable=YES
pasv_min_port=21100
pasv_max_port=21110

# Point FTP root to wordpress files
local_root=/var/www/html